### ISSUE TITLE
"Saint Seiya" mapping update

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#153]
Looks like 'Saint Seiya' is only season 1 -> season 3.
```
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=826

73ep - https://www.thetvdb.com/series/saint-seiya/seasons/1
26ep - https://www.thetvdb.com/series/saint-seiya/seasons/2
15ep - https://www.thetvdb.com/series/saint-seiya/seasons/3
```
```xml
FROM:
  <anime anidbid="826" tvdbid="72775" defaulttvdbseason="a" episodeoffset="" tmdbid="" imdbid="">
    <name>Saint Seiya</name>
  </anime>
TO:
  <anime anidbid="826" tvdbid="72775" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Saint Seiya</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="2" start="74" end="99" offset="-73"/>
      <mapping anidbseason="1" tvdbseason="3" start="100" end="114" offset="-99"/>
    </mapping-list>
  </anime>
```

**Comment by ScudLee** [comment]
I don't see the issue here.  
The 'a' in the defaulttvdbseason means to use the absolute numbers on thetvdb, and episodes 1-114 on anidb (i.e. all of them) match the absolute numbered episodes 1-114 on the tvdb exactly.

The mapping is only _from_ anidb _to_ thetvdb.  The fact that the absolute numbering extends past 114 on thetvdb shouldn't, and doesn't, matter.  Adding an extra episode 115 to your Saint Seiya folder shouldn't erroneously add an episode with details from S04E01 on thetvdb, because there's no episode 115 on anidb to start with.

(This comment also applies to #154.)

**Comment by sixtenbe** [comment]
Is it just me reading it wrong, but it looks like tvdb removed the absolute numbering for this series and the series mentioned in #154. See [S02E8](https://www.thetvdb.com/series/saint-seiya/episodes/96016). With this change in tvdb I believe this issue is an actual issue and the full mapping is needed.

Maybe this change is due to the large time gaps between seasons, which AniDB would correctly add as a separate entry with its own episode numbering, breaking the idea of an absolute numbering after season 3, so no season gets it?

I'm going to leave it like this for now, but if I get no response I'll try and remember to change it after the next season is added.

**Comment by sixtenbe** [comment]
When using the API it appears the absolute mapping do remain. I haven't done this 100% since I don't want to write a interpreter to pull out the data 100% correct, but the episode ids appear to be followed with a absolute episode number.

So it appears that the web page no longer shows the absolute numbering, but it remains on the API side.

In the future if someone wants to change a (defaulttvdbseason="a") mapping I'd hope it comes with a verification that this is actually an issue and not just appears so, due to web page not exposing the information correctly.
