### ISSUE TITLE
Monogatari Mapping Hell

### ISSUE THREAD

**Issue by thekramnella** [ScudLee/anime-lists#163]
```
  <anime anidbid="6327" tvdbid="102261" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Bakemonogatari</name>
    <mapping-list>
     <mapping anidbseason="0" tvdbseason="1">;1-13;2-14;3-15;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="8357" tvdbid="102261" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Kizumonogatari</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="0">;1-2;2-19;3-20;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="8658" tvdbid="102261" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Nisemonogatari</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="2"/>
    </mapping-list>
  </anime>
  <anime anidbid="9453" tvdbid="102261" defaulttvdbseason="0" episodeoffset="2" tmdbid="" imdbid="">
    <name>Nekomonogatari (Black): Tsubasa Family</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="3">;2-1;3-2;4-3;5-4;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="9183" tvdbid="102261" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
    <name>Monogatari Series: Second Season</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="4">;6-0;11-0;16-0;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="10046" tvdbid="102261" defaulttvdbseason="0" episodeoffset="9" tmdbid="" imdbid="">
    <name>Hanamonogatari: Suruga Devil</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="5"/>
    </mapping-list>
  </anime>
  <anime anidbid="10891" tvdbid="102261" defaulttvdbseason="0" episodeoffset="14" tmdbid="" imdbid="">
    <name>Tsukimonogatari</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="6" start="2" end="5" offset="-1"/>
    </mapping-list>
  </anime>
  <anime anidbid="11350" tvdbid="102261" defaulttvdbseason="4" episodeoffset="" tmdbid="" imdbid="">
    <name>Owarimonogatari</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="7"/>
    </mapping-list>
  </anime>
  <anime anidbid="11827" tvdbid="102261" defaulttvdbseason="0" episodeoffset="20" tmdbid="" imdbid="">
    <name>Koyomimonogatari</name>
    <mapping-list>
     <mapping anidbseason="1" tvdbseason="8"/>
    </mapping-list>
  </anime>
```
I believe I have all this right, let me know if this is wrong because I honestly barely have an idea what I'm doing lmao. I'm just trying to account for the horrendous way that tvdb sorted this series. That said, Owarimonogatari (2017) is so jacked on anidb that I don't even know where to begin mapping it.

Essentially, I'm trying to organize it like this:

Specials

1. Episode 5.5 (Recap) (2009)
2. Kizumonogatari Part 1: Tekketsu (2016) - Movie
3. Kizumonogatari Part 2: Nekketsu (2016) - Movie
4. Kizumonogatari Part 3: Reiketsu (2017) - Movie
5. Episode 4.5 (Araragi Koyomi's Story) (2017)
6. Zoku Owarimonogatari (2018) - Movie

Seasons

1. Bakemonogatari (2009) - 15eps
2. Nisemonogatari (2012) - 11eps
3. Nekomonogatari Black (2012) - 4eps
4. Monogatari Series Second Season (2013) - 26eps
5. Hanamonogatari (2014) - 5eps
6. Tsukimonogatari (2014) - 4eps
7. Owarimonogatari (2015) - 13eps
8. Koyomimonogatari (2016) - 12 eps
9. Owarimonogatari Second Season (2017) - 7eps

The episode ordering is sourced from myanimelist and anidb.
Here is a visual guide with a by-episode breakdown and sources: https://imgur.com/gallery/Ung4t

**Comment by sixtenbe** [comment]
It seems you're mostly lost in what you're doing. For Bakemonogatari, Kizumonogatari, and Nisemonogatari you've supplied no change from current mapping.

With Nekomonogatari (Black): Tsubasa Family you've mapped them to the same entries as the first 4 episodes of Monogatari Series: Second Season, with the recaps of Monogatari Series: Second Season removed instead of their mappings to the summaries in tvdb season 0. Tsubasa Family arc of Nekomonogatari (Black):  is not the same as Tsubasa Tiger arc of Monogatari Series: Second Season.

Reading this far in it seems you've simply misunderstood the purpose of this mapping list. The purpose is to map the anidb entries to the correctly corresponding tvdb entry and not in any way to create some sort of order or organization. Organization is to be done on either AniDB or TVDB in accordance with their rules and guidelines for adding data. Where anidb orders their entries in respect with each other using this [graph tree](https://anidb.net/perl-bin/animedb.pl?show=rel&aid=6327)

Further it's quite obvious your mappings are wrong if you look at the release dates on the anidb entries vs the entries on tvdb, with the current mapping having identical release dates on anidb vs tvdb.

I'm closing this since you've misunderstood the purpose of this mapping list as something other than simply mapping AniDB entries to tvdb entries.

If there is some entry you feel is incorrectly mapped, I suggest you make a new issue. Just remember referencing watch order lists and season graphs is only a reference for where you might find corresponding AniDB entries in the TVDB entries and not a source for how to actually map them.

**Comment by thekramnella** [comment]
Yeah, I forgot to close the post after I figured out I couldn't actually reorder the series with this. My first stop was actually tvdb, but the series was locked. I put in a request and got a response that was essentially "the Monogatari series is too confusing for me to reorder now, but I'll reorder it chronologically once it has been completely adapted". Which will be wrong btw, the actual release order is not chronological on purpose. I've since done some custom work to pull the data and source it in a proper order though. Thanks for the response.
