### ISSUE TITLE
Black Lagoon

### ISSUE THREAD

**Issue by ZeroQI** [ScudLee/anime-lists#164]
It seems there was an error with the specials during last addition https://github.com/ScudLee/anime-lists/issues/54 as  anidb specials 1-4 should be mapped to tvdb specials 1-4
- anidb link: http://anidb.net/perl-bin/animedb.pl?show=anime&aid=3395
- thetvdb link: https://www.thetvdb.com/series/black-lagoon/seasons/0

Herer is my correction, adding explicitely specials 1 to 4
```
 <anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Black Lagoon</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-1;2-2;3-3;4-4;5-0;</mapping>
    </mapping-list>
  </anime>
```

**Comment by sixtenbe** [comment]
The mapping is already correct since anidb S specials are implicitly mapped to season 0 of tvdb with the same episode number i.e anidb S1 mapps to tvdb S0E1 by default. I see no reason to update the mapping.

See ScudLee on [issue 151](https://github.com/ScudLee/anime-lists/issues/151#issuecomment-431640847)

**Comment by sixtenbe** [comment]
I'm going to close this issue as dead and with no issue on this end.
