### ISSUE TITLE
Saiki Kusuo no Sainan (TV Special) mapping

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#251]
This [AniDB special](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=14189) is listed as [S0E96 in TVDB.](https://www.thetvdb.com/series/the-disastrous-life-of-saiki-k/episodes/6972873)

Current:

```
  <anime anidbid="14189" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Saiki Kusuo no Sainan (TV Special)</name>
  </anime>
```

Think it should be:

```
  <anime anidbid="14189" tvdbid="313435" defaulttvdbseason="0" episodeoffset="95" tmdbid="" imdbid="">
    <name>Saiki Kusuo no Sainan (TV Special)</name>
  </anime>
```

**Comment by sixtenbe** [comment]
The bigger thing to take note of is that Saiki Kusuo no Sainan (2016) has it's 95 first episodes in season 0 of tvdb, but the full 120 episodes can be found in season 1 as 5 anidb episodes per episode in tvdb season 1. 

For now I'll just nullmap the 96th episode to avoid overlap with the tv special and nullmap the web special from 2013.

**Comment by sven-7** [comment]
Yeah - that's a super confusing bit between the two.  AniDB wasn't consistent with how they did the second season. Appreciate you taking care of that.

**Comment by sixtenbe** [comment]
technically it would be correct to map it to season one and do a mapping list of:
`;1-1;2-1;3-1;4-1;5-1;6-2;7-2;8-2;9-2;10-2;......;111-23;112-23;113-23;114-23;115-23;116-24;117-24;118-24;119-24;120-24';`
and so on for all 120 episodes, but I'm not sure how worthwhile it would be to do that since tvdb have been a bit undecisive, with how they have 2 sets of correct mappings for the first 95 episodes.

**Comment by sven-7** [comment]
If I remember correctly, this was the compromise they came up with on the forum. Since I believe the shorts aired Mon-Thurs and the full set on Fri, they ended up doing both.  Since episodes more traditionally are in that 20-25 minute range they opted for the combo to be the main S1.  For some reason, I think S2 only aired as complete sets.  I've been leaning to TVDB for how they have S1 and S2 instead of AniDBs. 

Like you said tho, probably more trouble that it's worth.

**Comment by sixtenbe** [comment]
I already have the full string for mapping, as it's easy to generate with a few lines of code, so it's just a matter of pasting it to the mapping list of the entry.

I'm thinking a bit of just putting it as season 0 in the main line and then using mapping list to map all the episodes to season 1. Not yet sure if I'm going to do it though and if I do it it would probably be a commit with just that change and a explanation for it.

**Comment by sven-7** [comment]
Realized this was still an open ticket. @sixtenbe did you make any decisions on this?

**Comment by purposelycryptic** [comment]
So, the initial issue regarding the special was taken care of at some point, leaving us with this, which seems as it should be:

```xml
  <anime anidbid="14189" tvdbid="313435" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Saiki Kusuo no Sainan: Kanketsuhen</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-96;</mapping>
    </mapping-list>
  </anime>
```
No changes have been made as of yet regarding the 2016 series though, leaving roughly 1/4 of the series unmapped. So we have the choice of either fixing the TVDB entry, and adding the remaining episodes (after discussing it with a mod, as they tend to get very unhappy when things are modified without their knowledge or approval, since it stands to mess up people's metadata  in this case, the special randomly positioned at the end, despite episodes still missing that should have gone there), or changing the mapping to this, as @sixtenbe mentioned:

```xml
  <anime anidbid="12112" tvdbid="313435" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Saiki Kusuo no Sainan (2016)</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="1">;1-1;2-1;3-1;4-1;5-1;6-2;7-2;8-2;9-2;10-2;11-3;12-3;13-3;14-3;15-3;16-4;17-4;18-4;19-4;20-4;21-5;22-5;23-5;24-5;25-5;26-6;27-6;28-6;29-6;30-6;31-7;32-7;33-7;34-7;35-7;36-8;37-8;38-8;39-8;40-8;41-9;42-9;43-9;44-9;45-9;46-10;47-10;48-10;49-10;50-10;51-11;52-11;53-11;54-11;55-11;56-12;57-12;58-12;59-12;60-12;61-13;62-13;63-13;64-13;65-13;66-14;67-14;68-14;69-14;70-14;71-15;72-15;73-15;74-15;75-15;76-16;77-16;78-16;79-16;80-16;81-17;82-17;83-17;84-17;85-17;86-18;87-18;88-18;89-18;90-18;91-19;92-19;93-19;94-19;95-19;96-20;97-20;98-20;99-20;100-20;101-21;102-21;103-21;104-21;105-21;106-22;107-22;108-22;109-22;110-22;111-23;112-23;113-23;114-23;115-23;116-24;117-24;118-24;119-24;120-24;</mapping>
    </mapping-list>
  </anime>
```

It's a bit messy, granted, but, unlike the individual episodes that are listed in the Specials section, the ones in Season 1 have episode summaries and images. I'd personally lean in that direction, simply because I'm lazy, and the idea of writing 120 summaries of 5-minute episodes terrifies me (but I also hate episodes without summaries). I actually already have it like that in my HAMA mapping override file.

But one of the two should definitely be done, as the current state is just incomplete.

**Comment by purposelycryptic** [comment]
The [latest](https://forums.thetvdb.com/viewtopic.php?f=18&t=54236) I could find on the forums was from when it was mod-edited to the state it was in a few days ago, before the purge... And it isn't on the purge list either. This just keeps getting weirder.

**Comment by sixtenbe** [comment]
Decided to go with the full 5 Anidb Episodes to 1 TVDB episode mapping as seen in the commit [a13bbaa](https://github.com/ScudLee/anime-lists/commit/a13bbaa664a21d3d06f395f386f086b0cafd01a6)

**Comment by purposelycryptic** [comment]
Best choice given the options available, really.

**Comment by sven-7** [comment]
We'll likely need to update again now that a few new were added. TheTVDB is going to add the new Netflix episodes as specials 98-103.

**Comment by sven-7** [comment]
#308 should do it -- assuming nothing changes.
